[data]
# User information
email = "droo@axol.io"
name = "hydepwns"

# Tool configurations
rbenv = false
ohmyzsh = true
nvm = true
nodejs = true
asdf = true
elixir = true
erlang = false
lua = true
direnv = true
devenv = false
nix = true
llvm = false
postgres = false
psql = false
foundry = false
huff = false
solana = false
orbstack = false
work = false
personal = false

# Platform-specific
brewPrefix = "/opt/homebrew"