# mise global configuration
# See: https://mise.jdx.dev/configuration.html

[tools]
node = "lts"
python = "3.10.13"
erlang = "26.2.4"
elixir = "1.18.3-otp-26"

[settings]
verbose = false
always_keep_download = true

[env]
MISE_NODE_VERIFY = "false"
